### ISSUE TITLE
HTTPS url is showing "info" / "insure" icon

### ISSUE THREAD

**Issue by studyingMole** [decentraland/web#11]
On Chrome the HTTPS endpoint appears insecure.

According to Chrome console, it's due to mixed content. Warning in Chrome:

`Mixed Content: The page at 'https://decentraland.org/#faqs' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://decentraland.us15.list-manage.com/subscribe?u=6f74047a4693dbc82dc4f3131&id=da075b1985'. This endpoint should be made available over a secure connection.` 

The `http://decentraland.us15.list-manage.com` endpoint should be accessible via HTTPS.

**Comment by martriay** [comment]
Fixed by @eordano in https://github.com/decentraland/web/commit/621c92c0a31e7fd89f7cd21ea7caeb041b6e6f6b
